### ISSUE TITLE
FBO: not complete 36059 in macos m1

### ISSUE THREAD

**Issue by furmanlukasz** [patriciogonzalezvivo/lygia_examples#1]
While trying 3D examples e.g. `glslViewer assets/dragon.obj lighting_ssr.frag -e camera_position,-1.43923,0.891203,1.98093 -C assets/uffizi_cross.hdr -e dynamic_shadows,on -l ` I get error `FBO: not complete 36059`. This is also happening for other complex 3D exmaples.

**Comment by patriciogonzalezvivo** [comment]
Hi! Question, what version of glslViewer you have ( `glslViewer -v`  ) ? What OS? 
As a side note, there where some new features like GBuffers to make those more complex examples possible. You will need 3.0.1 or up to make it work.

**Comment by furmanlukasz** [comment]
Hi Patricio! Version 3.0.1, I have installed everything yesterday. OS is Monterey 12.6. Also in the first example I have only dots no lines in shader viewer, here is screenshot: https://ibb.co/LQndT75. 
Here are more outputs from this shaders:
https://ibb.co/W5dtftf
https://ibb.co/LQndT75
https://ibb.co/wsQqNtk
https://ibb.co/hBrKbpv
https://ibb.co/5jLF5TZ

**Comment by furmanlukasz** [comment]
Maybe it can be related to error that I have while cloning repository:
```

(base) ➜  a git clone --recursive https://github.com/patriciogonzalezvivo/lygia_examples.git

Cloning into 'lygia_examples'...
remote: Enumerating objects: 512, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 512 (delta 58), reused 77 (delta 26), pack-reused 399
Receiving objects: 100% (512/512), 19.56 MiB | 10.59 MiB/s, done.
Resolving deltas: 100% (279/279), done.
Submodule 'lygia' (git@github.com:patriciogonzalezvivo/lygia.git) registered for path 'lygia'
Cloning into '/Users/luki/Documents/GitHub/a/lygia_examples/lygia'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:patriciogonzalezvivo/lygia.git' into submodule path '/Users/luki/Documents/GitHub/a/lygia_examples/lygia' failed
Failed to clone 'lygia'. Retry scheduled
Cloning into '/Users/luki/Documents/GitHub/a/lygia_examples/lygia'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:patriciogonzalezvivo/lygia.git' into submodule path '/Users/luki/Documents/GitHub/a/lygia_examples/lygia' failed
Failed to clone 'lygia' a second time, aborting
```

after getting this I did as you suggested here: https://github.com/ShaderCamp/shader_prototyping_2022

```
If you already clone it with out the --recursive flag, just do

git pull
git submodule init
git submodule update
```

**Comment by patriciogonzalezvivo** [comment]
hi! I got a hold of a mac, and I can replicate the FBO error. I will work on a solution for it.
For the second issue, seams you don't have your ssh keys added to your github account... or you don't have a github account all together. Is that right?

**Comment by furmanlukasz** [comment]
Thank you Patricio! Oh, yes that's right, thats was ssh key - my mistake.

**Comment by furmanlukasz** [comment]
Patricio thank you very much for the quick fix! Now it works great. I will close the issue now. See ya at 25 October on yours SHADER PROTOTYPING course!
![Zrzut ekranu 2022-10-21 o 16 39 32](https://user-images.githubusercontent.com/49567833/197222907-ff6d02e5-1c79-466f-9b7c-f9426856ed4a.png)
